### ISSUE TITLE
glitch.social changes

### ISSUE THREAD

**Issue by clarfonthey** [florence-social/mastodon-fork#3]
Website: https://glitch-soc.github.io/docs/
Repository: https://github.com/glitch-soc/mastodon/

This is going to be the parent issue for all glitch.social changes to be incorporated.

- [ ] Hiding media behind subjects/CWs: #4 
- [ ] Fullwidth images and videos: #5 
- [ ] Image letterboxing: #6 
- [ ] App settings modal: #7 
- [ ] Collapsible toots: #8 
- [ ] Collapsible notifications: #9
- [ ] Visibility icons on toots: #10 
- [ ] Non-federated toots: #11 
- [ ] Threaded posting mode: #12 
- [ ] Extra data-* attributes on toots: #13 
- [ ] Theming: #14 
- [ ] Bookmarks: #15 
- [ ] Doodles: #16
