### ISSUE TITLE
Tracking issue for hardcoded settings to admin configurables with defaults 

### ISSUE THREAD

**Issue by mal0ki** [florence-social/mastodon-fork#80]
The title describes it, just adding this as an issue, to remind us that we want to go through all the hardcoded values (like character count for both posts and bios etc,) and decide which we want to provide as configurable with defaults settings instead. 

- [x] Character Count for posts
- [x] Character Count for bios
- [ ] MaxNumber of Pinned posts
- [ ] MaxNumber of profile metadata fields ( https://github.com/florence-social/mastodon-fork/issues/43 )
- [ ] Flavour names for posts, boosts, favs etc.
- [ ] Favicon for instance

Feel free to add to the check list here, and suggest things that you've wanted to see change to make it easier to create your own flavour of Mastodon. 

For any folks with edit rights, feel free to edit this post with new items to the check list, as appropriate.

**Comment by ryliejamesthomas** [comment]
Maximum number of ~~bio fields~~ profile metadata fields

(edited to use proper terminology)

**Comment by mal0ki** [comment]
Configurable flavour names for posts, boosts, favs etc.

**Comment by mal0ki** [comment]
Profile Meta data reference https://github.com/florence-social/mastodon-fork/issues/43

**Comment by ryliejamesthomas** [comment]
Got another one: ability to upload favicon from admin panel. 'Cause at the moment if you're on Mastohost you're stuck with the default, and replacing the favicon is typically trivial.
